### ISSUE TITLE
在debug模式下可用，在release模式下不起作用

### ISSUE THREAD

**Issue by guolidaxian** [cj123195/flutter_aiui#1]
你好，例子写的挺好，非常感谢您的分享！！我在debug模式下调试了一下可用，但在release模式下，打包成apk安装后，不起作用，需要特别的设计吗

**Comment by guolidaxian** [comment]
报这个错：E/flutter ( 8866): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: PlatformException(error, Attempt to invoke virtual method 'void d.o.a.b.o(io.flutt
er.plugin.common.MethodChannel$Result, java.lang.String)' on a null object reference, null, java.lang.NullPointerException: Attempt to invoke virtual method 'void d.o.
a.b.o(io.flutter.plugin.common.MethodChannel$Result, java.lang.String)' on a null object reference
E/flutter ( 8866):      at d.o.a.c.onMethodCall(Unknown Source:312)
E/flutter ( 8866):      at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(Unknown Source:17)
E/flutter ( 8866):      at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(Unknown Source:57)
E/flutter ( 8866):      at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(Unknown Source:4)
E/flutter ( 8866):      at android.os.MessageQueue.nativePollOnce(Native Method)
E/flutter ( 8866):      at android.os.MessageQueue.next(MessageQueue.java:363)
E/flutter ( 8866):      at android.os.Looper.loop(Looper.java:176)
E/flutter ( 8866):      at android.app.ActivityThread.main(ActivityThread.java:8668)
E/flutter ( 8866):      at java.lang.reflect.Method.invoke(Native Method)
E/flutter ( 8866):      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
E/flutter ( 8866):      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1109)
E/flutter ( 8866): )
E/flutter ( 8866): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:597)
E/flutter ( 8866): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:158)
E/flutter ( 8866): <asynchronous suspension>
E/flutter ( 8866): #2      FlutterAIUI.startSpeak (package:flutter_aiui/flutter_aiui.dart:86)
E/flutter ( 8866): <asynchronous suspension>

**Comment by cj123195** [comment]
> 报这个错：E/flutter ( 8866): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: PlatformException(error, Attempt to invoke virtual method 'void d.o.a.b.o(io.flutt er.plugin.common.MethodChannel$Result, java.lang.String)' on a null object reference, null, java.lang.NullPointerException: Attempt to invoke virtual method 'void d.o. a.b.o(io.flutter.plugin.common.MethodChannel$Result, java.lang.String)' on a null object reference E/flutter ( 8866): at d.o.a.c.onMethodCall(Unknown Source:312) E/flutter ( 8866): at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(Unknown Source:17) E/flutter ( 8866): at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(Unknown Source:57) E/flutter ( 8866): at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(Unknown Source:4) E/flutter ( 8866): at android.os.MessageQueue.nativePollOnce(Native Method) E/flutter ( 8866): at android.os.MessageQueue.next(MessageQueue.java:363) E/flutter ( 8866): at android.os.Looper.loop(Looper.java:176) E/flutter ( 8866): at android.app.ActivityThread.main(ActivityThread.java:8668) E/flutter ( 8866): at java.lang.reflect.Method.invoke(Native Method) E/flutter ( 8866): at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513) E/flutter ( 8866): at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1109) E/flutter ( 8866): ) E/flutter ( 8866): #0 StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:597) E/flutter ( 8866): #1 MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:158) E/flutter ( 8866): E/flutter ( 8866): #2 FlutterAIUI.startSpeak (package:flutter_aiui/flutter_aiui.dart:86) E/flutter ( 8866):

不需要什么特别的配置，目前项目的release版本没有出现类似的问题，你这边是在startSpeak的时候报了空指针错误，可以自行调试一下，看参数有没有配置正确。

**Comment by guolidaxian** [comment]
谢谢！我没有做任何修改，只是下载了例子，debug模式下能运行，然后用  flutter run --release 打包安装后，就出现问题了。初始化界面时，报了以下错误：

 [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: MissingPluginException(No implementation found for method init on channel flutter_
aiui)
E/flutter ( 5072): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:154)
E/flutter ( 5072): <asynchronous suspension>
E/flutter ( 5072): #1      FlutterAIUI.init (package:flutter_aiui/flutter_aiui.dart:70)
E/flutter ( 5072): <asynchronous suspension>
E/flutter ( 5072):

**Comment by guolidaxian** [comment]
对环境有特

> 谢谢！我没有做任何修改，只是下载了例子，debug模式下能运行，然后用 flutter run --release 打包安装后，就出现问题了。初始化界面时，报了以下错误：
> 
> [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: MissingPluginException(No implementation found for method init on channel flutter_ aiui) E/flutter ( 5072): #0 MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:154) E/flutter ( 5072): E/flutter ( 5072): #1 FlutterAIUI.init (package:flutter_aiui/flutter_aiui.dart:70) E/flutter ( 5072): E/flutter ( 5072):

对环境有特殊要求吗？好像是插件无法加载

**Comment by guolidaxian** [comment]
谢谢，问题已经解决，需要把混淆关了就可以了，解决方法如下：
   buildTypes {
        release {
            // TODO: Add your own signing config for the release build.
            // Signing with the debug keys for now, so `flutter run --release` works.
            signingConfig signingConfigs.debug
            //资源缩减

            shrinkResources false// 

            minifyEnabled false//源代码混淆 true----解决了  MissingPluginException 报错， 
        }
    }
